name: Run Blue-Tone Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Start Bot
      run: node index.js
      env:
        ADMIN: '61594424694266'
        PREFIX: '!'
